@startuml message
'class diagram
left to right direction
skinparam linetype ortho

class Message <<Serializable Record>> {
  - contentCode: ContentCode
  - requestUID: Long
  - serviceUID: Long
  - fingerprint: Long
  - body: byte[]
}
hide Message methods
@enduml
